server:
  port: 8888

spring:
  application:
    name: gm-hystrix-ribbon-server

logging:
  config: classpath:logback.xml

eureka:
  client:
    serviceUrl: 
      defaultZone: http://ms.m.com:7777/eureka/
  instance: 
    lease-renewal-interval-in-seconds: 1 
    lease-expiration-duration-in-seconds: 2 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
    prefer-ip-address: true 


